Libraries

In [3]:
import pandas as pd

Connecting to Data

In [4]:
Reels=pd.read_excel("C:\\Users\\omnia\\OneDrive\\Desktop\\Data_Engineering\\Reals_Project\\survey_3289_cleaned_english (final).xlsx")

Dataset Structure

In [5]:
Reels

,timestamp,age_group,gender,region,marital_status,occupation,education_level,primary_platform,daily_watch_hours,content_type,...,family_opinion,reason_for_watching,social_media_without_reels,purchased_from_video,purchase_reason,purchase_influence_level,rewatched_before_purchase,watch_intensity_score,user_segment,content_count
0,2026-03-09 23:29:26.782,25-34,Male,Greater Cairo,Single,Employee (Gov/Private),University Graduate,TikTok,1-2 hrs,Comedy & Entertainment | Educational & Cultural,...,Supportive (edutainment),Mood improvement,Would decrease a lot,Never,Visual attraction,Moderate influence,Usually,3,Moderate User,2
1,2026-03-10 00:44:53.913,18-24,Female,Greater Cairo,Single,Student,University Student,Facebook Reels,3+ hrs,News & Current Affairs | Religious | Comedy & ...,...,Complain – causes conflicts,Killing time,Would decrease a lot,"Yes, often (easily influenced)",Persuasive content,Moderate influence,Never,5,Heavy User,3
2,2026-03-10 18:58:55.116,25-34,Male,Greater Cairo,Single,Freelancer,Postgraduate,TikTok,1-2 hrs,News & Current Affairs | Comedy & Entertainmen...,...,Advise me to reduce usage,Mood improvement,Would decrease slightly,Like items but never buy,Genuine need,Moderate influence,Sometimes,3,Moderate User,5
3,2026-03-10 19:01:01.164,25-34,Male,Greater Cairo,Single,Freelancer,Postgraduate,Facebook Reels,3+ hrs,Religious | Comedy & Entertainment | Education...,...,Advise me to reduce usage,Entertainment,Would decrease a lot,Once or twice,Persuasive content,Low influence,Sometimes,5,Heavy User,4
4,2026-03-10 19:05:55.748,18-24,Female,Greater Cairo,Single,Employee (Gov/Private),University Graduate,Facebook Reels,3+ hrs,Comedy & Entertainment,...,Indifferent,Entertainment,Would decrease a lot,Once or twice,Genuine need,Moderate influence,Always,5,Heavy User,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3284,2026-06-30 12:22:11.035,25-34,Male,Upper Egypt,Single,Freelancer,Postgraduate,Facebook Reels,2-3 hrs,Self-development,...,Advise me to reduce usage,Mood improvement,Would decrease slightly,Once or twice,Genuine need,Moderate influence,Rarely,4,Heavy User,1
3285,2026-06-30 19:28:32.050,18-24,Female,North Coast / Red Sea,Single,Student,University Student,Instagram Reels | TikTok,3+ hrs,Comedy & Entertainment | Fashion & Beauty | Mu...,...,Complain – causes conflicts,Entertainment,Would decrease slightly,Once or twice,Genuine need,Moderate influence,Always,5,Heavy User,3
3286,2026-06-30 20:25:06.080,25-34,Female,Greater Cairo,Married with Children,Employee (Gov/Private),University Graduate,Facebook Reels,30-60 min,News & Current Affairs | Religious | Comedy & ...,...,Indifferent,Killing time,Would not change,Once or twice,Genuine need,Low influence,Sometimes,2,Light User,3
3287,2026-06-30 21:08:37.886,18-24,Female,Greater Cairo,Single,Student,University Student,TikTok,3+ hrs,Self-development | Fashion & Beauty | Music & ...,...,Indifferent,Entertainment,Would decrease slightly,Like items but never buy,N/A – Never purchased,Low influence,Sometimes,5,Heavy User,3
3288,2026-06-30 21:48:28.885,18-24,Male,Greater Cairo,Single,Freelancer,University Student,Facebook Reels,3+ hrs,Comedy & Entertainment | Sports | Gaming,...,Indifferent,Entertainment,Would not change,"Yes, often (easily influenced)",Visual attraction,Moderate influence,Always,5,Heavy User,3

How To Analysis DataFrames

In [6]:
Reels.head()  #it shows First N=5 Rows

,timestamp,age_group,gender,region,marital_status,occupation,education_level,primary_platform,daily_watch_hours,content_type,...,family_opinion,reason_for_watching,social_media_without_reels,purchased_from_video,purchase_reason,purchase_influence_level,rewatched_before_purchase,watch_intensity_score,user_segment,content_count
0,2026-03-09 23:29:26.782,25-34,Male,Greater Cairo,Single,Employee (Gov/Private),University Graduate,TikTok,1-2 hrs,Comedy & Entertainment | Educational & Cultural,...,Supportive (edutainment),Mood improvement,Would decrease a lot,Never,Visual attraction,Moderate influence,Usually,3,Moderate User,2
1,2026-03-10 00:44:53.913,18-24,Female,Greater Cairo,Single,Student,University Student,Facebook Reels,3+ hrs,News & Current Affairs | Religious | Comedy & ...,...,Complain – causes conflicts,Killing time,Would decrease a lot,"Yes, often (easily influenced)",Persuasive content,Moderate influence,Never,5,Heavy User,3
2,2026-03-10 18:58:55.116,25-34,Male,Greater Cairo,Single,Freelancer,Postgraduate,TikTok,1-2 hrs,News & Current Affairs | Comedy & Entertainmen...,...,Advise me to reduce usage,Mood improvement,Would decrease slightly,Like items but never buy,Genuine need,Moderate influence,Sometimes,3,Moderate User,5
3,2026-03-10 19:01:01.164,25-34,Male,Greater Cairo,Single,Freelancer,Postgraduate,Facebook Reels,3+ hrs,Religious | Comedy & Entertainment | Education...,...,Advise me to reduce usage,Entertainment,Would decrease a lot,Once or twice,Persuasive content,Low influence,Sometimes,5,Heavy User,4
4,2026-03-10 19:05:55.748,18-24,Female,Greater Cairo,Single,Employee (Gov/Private),University Graduate,Facebook Reels,3+ hrs,Comedy & Entertainment,...,Indifferent,Entertainment,Would decrease a lot,Once or twice,Genuine need,Moderate influence,Always,5,Heavy User,1

In [7]:
Reels.shape   #it shows # of Rows x columns

(3289, 32)

In [8]:
Reels.index   #it shows start index & end index & step of dataframe

RangeIndex(start=0, stop=3289, step=1)

In [9]:
Reels["user_id"] = Reels.index

In [10]:
Reels.columns  #it shows name of each column

Index(['timestamp', 'age_group', 'gender', 'region', 'marital_status',
       'occupation', 'education_level', 'primary_platform',
       'daily_watch_hours', 'content_type', 'peak_usage_time', 'daily_opens',
       'voice_msg_behavior', 'usage_duration_since', 'content_relevance',
       'difficulty_closing_app', 'productivity_impact', 'sleep_impact',
       'feeling_after_closing', 'watching_companion',
       'behavior_while_watching', 'phone_during_family', 'family_opinion',
       'reason_for_watching', 'social_media_without_reels',
       'purchased_from_video', 'purchase_reason', 'purchase_influence_level',
       'rewatched_before_purchase', 'watch_intensity_score', 'user_segment',
       'content_count', 'user_id'],
      dtype='object')

In [11]:
Reels.dtypes   #it shows datatype of each column

timestamp                     datetime64[ns]
age_group                             object
gender                                object
region                                object
marital_status                        object
occupation                            object
education_level                       object
primary_platform                      object
daily_watch_hours                     object
content_type                          object
peak_usage_time                       object
daily_opens                           object
voice_msg_behavior                    object
usage_duration_since                  object
content_relevance                     object
difficulty_closing_app                object
productivity_impact                   object
sleep_impact                          object
feeling_after_closing                 object
watching_companion                    object
behavior_while_watching               object
phone_during_family                   object
family_opinion                        object
reason_for_watching                   object
social_media_without_reels            object
purchased_from_video                  object
purchase_reason                       object
purchase_influence_level              object
rewatched_before_purchase             object
watch_intensity_score                  int64
user_segment                          object
content_count                          int64
user_id                                int64
dtype: object

In [12]:
Reels["daily_opens"].unique()

array(['3-5 times/day', 'All day (lost count)', '6-10 times/day',
       '1-2 times/day'], dtype=object)

In [13]:
Reels.nunique() #No of unique values in each column

timestamp                     3289
age_group                        6
gender                           2
region                           6
marital_status                   4
occupation                       5
education_level                  7
primary_platform                35
daily_watch_hours                5
content_type                    96
peak_usage_time                  6
daily_opens                      4
voice_msg_behavior               4
usage_duration_since             5
content_relevance                4
difficulty_closing_app           4
productivity_impact              4
sleep_impact                     4
feeling_after_closing            3
watching_companion               5
behavior_while_watching          4
phone_during_family              4
family_opinion                   4
reason_for_watching              5
social_media_without_reels       5
purchased_from_video             4
purchase_reason                  5
purchase_influence_level         3
rewatched_before_purchase        5
watch_intensity_score            5
user_segment                     3
content_count                    6
user_id                       3289
dtype: int64

In [14]:
Reels.count() #No of non-null values of each column

timestamp                     3289
age_group                     3289
gender                        3289
region                        3289
marital_status                3289
occupation                    3289
education_level               3289
primary_platform              3289
daily_watch_hours             3289
content_type                  3289
peak_usage_time               3289
daily_opens                   3289
voice_msg_behavior            3263
usage_duration_since          3289
content_relevance             3289
difficulty_closing_app        3289
productivity_impact           3289
sleep_impact                  3289
feeling_after_closing         3289
watching_companion            3289
behavior_while_watching       3289
phone_during_family           3289
family_opinion                3289
reason_for_watching           3289
social_media_without_reels    3289
purchased_from_video          3289
purchase_reason               3289
purchase_influence_level      3289
rewatched_before_purchase     3289
watch_intensity_score         3289
user_segment                  3289
content_count                 3289
user_id                       3289
dtype: int64

In [15]:
Reels["primary_platform"].unique()

array(['TikTok', 'Facebook Reels', 'Instagram Reels', 'X/Twitter',
       'Facebook Reels | TikTok | YouTube Shorts', 'YouTube Shorts',
       'Facebook Reels | Instagram Reels | TikTok',
       'Facebook Reels | Instagram Reels',
       'Facebook Reels | YouTube Shorts',
       'Facebook Reels | Instagram Reels | WhatsApp',
       'Instagram Reels | YouTube Shorts', 'Instagram Reels | TikTok',
       'Other', 'Facebook Reels | Instagram Reels | Threads',
       'Facebook Reels | TikTok', 'X/Twitter | LinkedIn',
       'TikTok | YouTube Shorts',
       'Facebook Reels | Instagram Reels | YouTube Shorts | Reddit | YouTube',
       'WhatsApp | Facebook',
       'Facebook Reels | Instagram Reels | YouTube Shorts',
       'YouTube Shorts | YouTube', 'WhatsApp', 'Reading',
       'Facebook Reels | Instagram Reels | TikTok | YouTube Shorts',
       'WhatsApp | Telegram', 'Lectures/Study',
       'YouTube Shorts | Study/Research', 'YouTube', 'TV',
       'Instagram Reels | Snapchat Spotlight',
       'Instagram Reels | TikTok | Snapchat Spotlight',
       'YouTube | Gaming', 'Threads',
       'Facebook Reels | Instagram Reels | TikTok | YouTube Shorts | Snapchat Spotlight',
       'Instagram Reels | Google Search'], dtype=object)

In [16]:
Reels["content_type"].unique()

array(['Comedy & Entertainment | Educational & Cultural',
       'News & Current Affairs | Religious | Comedy & Entertainment',
       'News & Current Affairs | Comedy & Entertainment | Educational & Cultural | Self-development | Sports',
       'Religious | Comedy & Entertainment | Educational & Cultural | Music & Dance',
       'Comedy & Entertainment',
       'News & Current Affairs | Religious | Comedy & Entertainment | Self-development',
       'Comedy & Entertainment | Self-development',
       'Religious | Comedy & Entertainment | Sports',
       'News & Current Affairs | Religious | Comedy & Entertainment | Educational & Cultural',
       'News & Current Affairs | Comedy & Entertainment | Self-development | Fashion & Beauty',
       'Comedy & Entertainment | Sports | Gaming',
       'News & Current Affairs | Religious | Comedy & Entertainment | Educational & Cultural | Self-development | Sports | Cooking | Music & Dance | Gaming',
       'News & Current Affairs | Comedy & Entertainment', 'Religious',
       'News & Current Affairs | Comedy & Entertainment | Cooking',
       'Religious | Comedy & Entertainment | Self-development',
       'News & Current Affairs | Educational & Cultural | Cooking',
       'News & Current Affairs | Religious | Educational & Cultural',
       'Self-development',
       'News & Current Affairs | Comedy & Entertainment | Gaming',
       'Religious | Comedy & Entertainment | Educational & Cultural',
       'News & Current Affairs | Religious | Cooking',
       'Comedy & Entertainment | Sports | Cooking',
       'Comedy & Entertainment | Self-development | Music & Dance',
       'Educational & Cultural | Self-development | Sports',
       'News & Current Affairs | Religious | Sports',
       'Comedy & Entertainment | Fashion & Beauty | Gaming',
       'News & Current Affairs',
       'News & Current Affairs | Comedy & Entertainment | Sports',
       'Religious | Educational & Cultural | Sports',
       'News & Current Affairs | Comedy & Entertainment | Educational & Cultural',
       'Religious | Educational & Cultural | Cooking',
       'Religious | Comedy & Entertainment | Fashion & Beauty',
       'News & Current Affairs | Sports | Cooking',
       'Religious | Comedy & Entertainment | Cooking',
       'Self-development | Music & Dance | Gaming',
       'Educational & Cultural | Sports | Gaming',
       'Religious | Comedy & Entertainment | Music & Dance',
       'Religious | Cooking | Fashion & Beauty',
       'News & Current Affairs | Religious | Fashion & Beauty',
       'Comedy & Entertainment | Fashion & Beauty | Music & Dance',
       'Comedy & Entertainment | Educational & Cultural | Cooking',
       'Comedy & Entertainment | Cooking | Fashion & Beauty',
       'News & Current Affairs | Educational & Cultural',
       'News & Current Affairs | Cooking | Fashion & Beauty',
       'Religious | Cooking',
       'News & Current Affairs | Religious | Self-development',
       'Comedy & Entertainment | Self-development | Fashion & Beauty',
       'Comedy & Entertainment | Gaming',
       'News & Current Affairs | Educational & Cultural | Fashion & Beauty',
       'News & Current Affairs | Comedy & Entertainment | Self-development',
       'Comedy & Entertainment | Self-development | Gaming',
       'Comedy & Entertainment | Sports', 'Cooking',
       'Comedy & Entertainment | Educational & Cultural | Self-development',
       'Comedy & Entertainment | Fashion & Beauty',
       'Religious | Educational & Cultural | Self-development',
       'Self-development | Cooking | Fashion & Beauty',
       'Cooking | Fashion & Beauty | Gaming',
       'Educational & Cultural | Cooking | Fashion & Beauty',
       'Religious | Educational & Cultural | Fashion & Beauty',
       'News & Current Affairs | Religious | Music & Dance',
       'Educational & Cultural | Self-development | Cooking',
       'Self-development | Sports | Fashion & Beauty',
       'Religious | Educational & Cultural',
       'Comedy & Entertainment | Self-development | Sports',
       'News & Current Affairs | Sports | Gaming',
       'Music & Dance | Gaming', 'Sports | Cooking | Gaming',
       'Religious | Self-development | Cooking',
       'Religious | Comedy & Entertainment',
       'News & Current Affairs | Cooking | Music & Dance',
       'News & Current Affairs | Educational & Cultural | Self-development',
       'Educational & Cultural | Fashion & Beauty | Music & Dance',
       'Religious | Comedy & Entertainment | Gaming',
       'News & Current Affairs | Sports | Music & Dance',
       'Religious | Self-development | Music & Dance',
       'Religious | Self-development | Sports',
       'Comedy & Entertainment | Sports | Music & Dance',
       'News & Current Affairs | Comedy & Entertainment | Music & Dance',
       'News & Current Affairs | Religious',
       'Religious | Sports | Gaming',
       'Comedy & Entertainment | Cooking | Gaming',
       'Religious | Self-development | Fashion & Beauty',
       'Educational & Cultural | Self-development | Fashion & Beauty',
       'News & Current Affairs | Self-development | Music & Dance',
       'Self-development | Fashion & Beauty | Music & Dance',
       'News & Current Affairs | Educational & Cultural | Sports',
       'Cooking | Fashion & Beauty | Music & Dance',
       'Educational & Cultural | Self-development | Gaming',
       'Cooking | Music & Dance | Gaming',
       'Comedy & Entertainment | Educational & Cultural | Fashion & Beauty',
       'Comedy & Entertainment | Self-development | Cooking',
       'Educational & Cultural',
       'Comedy & Entertainment | Educational & Cultural | Sports',
       'News & Current Affairs | Comedy & Entertainment | Fashion & Beauty'],
      dtype=object)

In [17]:
Reels.info() #it shows all information about each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3289 entries, 0 to 3288
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   timestamp                   3289 non-null   datetime64[ns]
 1   age_group                   3289 non-null   object
 2   gender                      3289 non-null   object
 3   region                      3289 non-null   object
 4   marital_status              3289 non-null   object
 5   occupation                  3289 non-null   object
 6   education_level             3289 non-null   object
 7   primary_platform            3289 non-null   object
 8   daily_watch_hours           3289 non-null   object
 9   content_type                3289 non-null   object
 10  peak_usage_time             3289 non-null   object
 11  daily_opens                 3289 non-null   object
 12  voice_msg_behavior          3263 non-null   object
 13  usage_duration_since        3289 non-null   object
 14  content_relevance           3289 non-null   object
 15  difficulty_closing_app      3289 non-null   object
 16  productivity_impact         3289 non-null   object
 17  sleep_impact                3289 non-null   object
 18  feeling_after_closing       3289 non-null   object
 19  watching_companion          3289 non-null   object
 20  behavior_while_watching     3289 non-null   object
 21  phone_during_family         3289 non-null   object
 22  family_opinion              3289 non-null   object
 23  reason_for_watching         3289 non-null   object
 24  social_media_without_reels  3289 non-null   object
 25  purchased_from_video        3289 non-null   object
 26  purchase_reason             3289 non-null   object
 27  purchase_influence_level    3289 non-null   object
 28  rewatched_before_purchase   3289 non-null   object
 29  watch_intensity_score       3289 non-null   int64
 30  user_segment                3289 non-null   object
 31  content_count               3289 non-null   int64
 32  user_id                     3289 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(29)
memory usage: 848.1+ KB

In [18]:
Reels.isnull().sum()  #it shows No of null values

timestamp                      0
age_group                      0
gender                         0
region                         0
marital_status                 0
occupation                     0
education_level                0
primary_platform               0
daily_watch_hours              0
content_type                   0
peak_usage_time                0
daily_opens                    0
voice_msg_behavior            26
usage_duration_since           0
content_relevance              0
difficulty_closing_app         0
productivity_impact            0
sleep_impact                   0
feeling_after_closing          0
watching_companion             0
behavior_while_watching        0
phone_during_family            0
family_opinion                 0
reason_for_watching            0
social_media_without_reels     0
purchased_from_video           0
purchase_reason                0
purchase_influence_level       0
rewatched_before_purchase      0
watch_intensity_score          0
user_segment                   0
content_count                  0
user_id                        0
dtype: int64

In [19]:
Reels.describe() #Summary Statistics

,timestamp,watch_intensity_score,content_count,user_id
count,3289,3289.000000,3289.000000,3289.000000
mean,2026-05-08 23:54:00.588278016,3.424141,2.766798,1644.000000
min,2026-03-09 23:29:26.782000,1.000000,1.000000,0.000000
25%,2026-04-16 12:25:01.803000064,2.000000,3.000000,822.000000
50%,2026-05-05 01:02:47.276999936,3.000000,3.000000,1644.000000
75%,2026-06-05 04:01:52.600000,5.000000,3.000000,2466.000000
max,2026-06-30 21:48:28.885000,5.000000,9.000000,3288.000000
std,NaN,1.269294,0.776035,949.596844

In [20]:
Reels.duplicated().sum()

np.int64(0)

Cleaning of content_type  & primary_platform

In [21]:
platforms = [
    'TikTok', 'Instagram Reels', 'YouTube Shorts',
    'Facebook Reels', 'Snapchat Spotlight'
]

def clean_platforms(platform):
    items = str(platform).split(' | ')
    items = [i for i in items if i in platforms]
    return ' | '.join(items)

Reels['primary_platform'] = Reels['primary_platform'].apply(clean_platforms)

In [22]:
Reels.dtypes

timestamp                     datetime64[ns]
age_group                             object
gender                                object
region                                object
marital_status                        object
occupation                            object
education_level                       object
primary_platform                      object
daily_watch_hours                     object
content_type                          object
peak_usage_time                       object
daily_opens                           object
voice_msg_behavior                    object
usage_duration_since                  object
content_relevance                     object
difficulty_closing_app                object
productivity_impact                   object
sleep_impact                          object
feeling_after_closing                 object
watching_companion                    object
behavior_while_watching               object
phone_during_family                   object
family_opinion                        object
reason_for_watching                   object
social_media_without_reels            object
purchased_from_video                  object
purchase_reason                       object
purchase_influence_level              object
rewatched_before_purchase             object
watch_intensity_score                  int64
user_segment                          object
content_count                          int64
user_id                                int64
dtype: object

In [23]:
Reels['primary_platform'] = Reels['primary_platform'].replace('', pd.NA)

In [24]:

Reels['primary_platform'] = Reels['primary_platform'].fillna('Other')

In [25]:
Reels["primary_platform"].unique()

array(['TikTok', 'Facebook Reels', 'Instagram Reels', 'Other',
       'Facebook Reels | TikTok | YouTube Shorts', 'YouTube Shorts',
       'Facebook Reels | Instagram Reels | TikTok',
       'Facebook Reels | Instagram Reels',
       'Facebook Reels | YouTube Shorts',
       'Instagram Reels | YouTube Shorts', 'Instagram Reels | TikTok',
       'Facebook Reels | TikTok', 'TikTok | YouTube Shorts',
       'Facebook Reels | Instagram Reels | YouTube Shorts',
       'Facebook Reels | Instagram Reels | TikTok | YouTube Shorts',
       'Instagram Reels | Snapchat Spotlight',
       'Instagram Reels | TikTok | Snapchat Spotlight',
       'Facebook Reels | Instagram Reels | TikTok | YouTube Shorts | Snapchat Spotlight'],
      dtype=object)

In [41]:
Reels["region"].unique()

array(['Greater Cairo', 'Abroad', 'Nile Delta', 'Upper Egypt',
       'North Coast / Red Sea', 'Canal Zone / Sinai'], dtype=object)

In [26]:
df_platform = (
    Reels.assign(primary_platform=Reels["primary_platform"].str.split("|"))
         .explode("primary_platform")
)

df_platform["primary_platform"] = df_platform["primary_platform"].str.strip()

df_platform = df_platform[["user_id", "primary_platform"]].reset_index(drop=True)

In [27]:
df_platform.head(50)

    user_id primary_platform
0         0           TikTok
1         1   Facebook Reels
2         2           TikTok
3         3   Facebook Reels
4         4   Facebook Reels
5         5   Facebook Reels
6         6           TikTok
7         7   Facebook Reels
8         8   Facebook Reels
9         9           TikTok
10       10   Facebook Reels
11       11   Facebook Reels
12       12   Facebook Reels
13       13           TikTok
14       14   Facebook Reels
15       15           TikTok
16       16   Facebook Reels
17       17  Instagram Reels
18       18  Instagram Reels
19       19            Other
20       20   Facebook Reels
21       21   Facebook Reels
22       21           TikTok
23       21   YouTube Shorts
24       22   YouTube Shorts
25       23   Facebook Reels
26       24   Facebook Reels
27       25   Facebook Reels
28       26   Facebook Reels
29       26  Instagram Reels
30       26           TikTok
31       27   Facebook Reels
32       27  Instagram Reels
33       28   YouTube Shorts
34       29   Facebook Reels
35       30   Facebook Reels
36       31  Instagram Reels
37       32   Facebook Reels
38       33   Facebook Reels
39       34  Instagram Reels
40       35   Facebook Reels
41       36  Instagram Reels
42       37   Facebook Reels
43       38   Facebook Reels
44       38   YouTube Shorts
45       39           TikTok
46       40           TikTok
47       41   Facebook Reels
48       42   Facebook Reels
49       43   Facebook Reels

In [28]:
df_platform["primary_platform"].value_counts()

primary_platform
Facebook Reels        1723
Instagram Reels       1065
TikTok                 880
YouTube Shorts         604
Other                  218
Snapchat Spotlight      61
Name: count, dtype: int64

In [29]:
Reels["content_type"].value_counts()

content_type
News & Current Affairs | Religious | Comedy & Entertainment                       200
News & Current Affairs | Comedy & Entertainment | Educational & Cultural          156
News & Current Affairs | Religious | Educational & Cultural                       139
News & Current Affairs | Religious | Sports                                       139
Comedy & Entertainment                                                            130
                                                                                 ...
Comedy & Entertainment | Sports | Music & Dance                                     7
Religious | Self-development | Music & Dance                                        6
Educational & Cultural | Self-development | Gaming                                  5
News & Current Affairs | Religious | Comedy & Entertainment | Self-development      5
Religious | Self-development | Sports                                               5
Name: count, Length: 96, dtype: int64

In [30]:
Content_type = Reels['content_type'].str.split('|')
Content_type  = Content_type .apply(
    lambda x: [i.strip() for i in x] if isinstance(x, list) else x
)

df_platform = df_platform.merge(
    Reels[['user_id', 'content_type']],
    on='user_id',
    how='left'
)

df_platform = df_platform.explode('content_type')

In [31]:
df_platform.head(30)

,user_id,primary_platform,content_type
0,0,TikTok,Comedy & Entertainment | Educational & Cultural
1,1,Facebook Reels,News & Current Affairs | Religious | Comedy & ...
2,2,TikTok,News & Current Affairs | Comedy & Entertainmen...
3,3,Facebook Reels,Religious | Comedy & Entertainment | Education...
4,4,Facebook Reels,Comedy & Entertainment
5,5,Facebook Reels,News & Current Affairs | Religious | Comedy & ...
6,6,TikTok,Comedy & Entertainment | Self-development
7,7,Facebook Reels,Religious | Comedy & Entertainment | Sports
8,8,Facebook Reels,Comedy & Entertainment
9,9,TikTok,News & Current Affairs | Religious | Comedy & ...
10,10,Facebook Reels,News & Current Affairs | Comedy & Entertainmen...
11,11,Facebook Reels,Comedy & Entertainment | Educational & Cultural
12,12,Facebook Reels,Comedy & Entertainment | Sports | Gaming
13,13,TikTok,News & Current Affairs | Religious | Comedy & ...
14,14,Facebook Reels,News & Current Affairs | Comedy & Entertainment
15,15,TikTok,Religious
16,16,Facebook Reels,News & Current Affairs | Comedy & Entertainmen...
17,17,Instagram Reels,Religious | Comedy & Entertainment | Self-deve...
18,18,Instagram Reels,News & Current Affairs | Educational & Cultura...
19,19,Other,News & Current Affairs | Religious | Education...
20,20,Facebook Reels,Self-development
21,21,Facebook Reels,News & Current Affairs | Comedy & Entertainmen...
22,21,TikTok,News & Current Affairs | Comedy & Entertainmen...
23,21,YouTube Shorts,News & Current Affairs | Comedy & Entertainmen...
24,22,YouTube Shorts,Religious | Comedy & Entertainment | Education...
25,23,Facebook Reels,News & Current Affairs | Religious | Cooking
26,24,Facebook Reels,Comedy & Entertainment | Sports | Cooking
27,25,Facebook Reels,Comedy & Entertainment | Self-development | Mu...
28,26,Facebook Reels,Religious | Comedy & Entertainment | Education...
29,26,Instagram Reels,Religious | Comedy & Entertainment | Education...

In [32]:
#df_platform.to_excel("C:\\Users\\omnia\\OneDrive\\Desktop\\Data_Engineering\\Reals_Project\\df_platform.xlsx", index=False)

In [33]:
Reels

,timestamp,age_group,gender,region,marital_status,occupation,education_level,primary_platform,daily_watch_hours,content_type,...,reason_for_watching,social_media_without_reels,purchased_from_video,purchase_reason,purchase_influence_level,rewatched_before_purchase,watch_intensity_score,user_segment,content_count,user_id
0,2026-03-09 23:29:26.782,25-34,Male,Greater Cairo,Single,Employee (Gov/Private),University Graduate,TikTok,1-2 hrs,Comedy & Entertainment | Educational & Cultural,...,Mood improvement,Would decrease a lot,Never,Visual attraction,Moderate influence,Usually,3,Moderate User,2,0
1,2026-03-10 00:44:53.913,18-24,Female,Greater Cairo,Single,Student,University Student,Facebook Reels,3+ hrs,News & Current Affairs | Religious | Comedy & ...,...,Killing time,Would decrease a lot,"Yes, often (easily influenced)",Persuasive content,Moderate influence,Never,5,Heavy User,3,1
2,2026-03-10 18:58:55.116,25-34,Male,Greater Cairo,Single,Freelancer,Postgraduate,TikTok,1-2 hrs,News & Current Affairs | Comedy & Entertainmen...,...,Mood improvement,Would decrease slightly,Like items but never buy,Genuine need,Moderate influence,Sometimes,3,Moderate User,5,2
3,2026-03-10 19:01:01.164,25-34,Male,Greater Cairo,Single,Freelancer,Postgraduate,Facebook Reels,3+ hrs,Religious | Comedy & Entertainment | Education...,...,Entertainment,Would decrease a lot,Once or twice,Persuasive content,Low influence,Sometimes,5,Heavy User,4,3
4,2026-03-10 19:05:55.748,18-24,Female,Greater Cairo,Single,Employee (Gov/Private),University Graduate,Facebook Reels,3+ hrs,Comedy & Entertainment,...,Entertainment,Would decrease a lot,Once or twice,Genuine need,Moderate influence,Always,5,Heavy User,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3284,2026-06-30 12:22:11.035,25-34,Male,Upper Egypt,Single,Freelancer,Postgraduate,Facebook Reels,2-3 hrs,Self-development,...,Mood improvement,Would decrease slightly,Once or twice,Genuine need,Moderate influence,Rarely,4,Heavy User,1,3284
3285,2026-06-30 19:28:32.050,18-24,Female,North Coast / Red Sea,Single,Student,University Student,Instagram Reels | TikTok,3+ hrs,Comedy & Entertainment | Fashion & Beauty | Mu...,...,Entertainment,Would decrease slightly,Once or twice,Genuine need,Moderate influence,Always,5,Heavy User,3,3285
3286,2026-06-30 20:25:06.080,25-34,Female,Greater Cairo,Married with Children,Employee (Gov/Private),University Graduate,Facebook Reels,30-60 min,News & Current Affairs | Religious | Comedy & ...,...,Killing time,Would not change,Once or twice,Genuine need,Low influence,Sometimes,2,Light User,3,3286
3287,2026-06-30 21:08:37.886,18-24,Female,Greater Cairo,Single,Student,University Student,TikTok,3+ hrs,Self-development | Fashion & Beauty | Music & ...,...,Entertainment,Would decrease slightly,Like items but never buy,N/A – Never purchased,Low influence,Sometimes,5,Heavy User,3,3287
3288,2026-06-30 21:48:28.885,18-24,Male,Greater Cairo,Single,Freelancer,University Student,Facebook Reels,3+ hrs,Comedy & Entertainment | Sports | Gaming,...,Entertainment,Would not change,"Yes, often (easily influenced)",Visual attraction,Moderate influence,Always,5,Heavy User,3,3288

In [34]:
Reels["content_type"].value_counts()

content_type
News & Current Affairs | Religious | Comedy & Entertainment                       200
News & Current Affairs | Comedy & Entertainment | Educational & Cultural          156
News & Current Affairs | Religious | Educational & Cultural                       139
News & Current Affairs | Religious | Sports                                       139
Comedy & Entertainment                                                            130
                                                                                 ...
Comedy & Entertainment | Sports | Music & Dance                                     7
Religious | Self-development | Music & Dance                                        6
Educational & Cultural | Self-development | Gaming                                  5
News & Current Affairs | Religious | Comedy & Entertainment | Self-development      5
Religious | Self-development | Sports                                               5
Name: count, Length: 96, dtype: int64

In [35]:
mode_value = Reels['voice_msg_behavior'].mode()[0]
Reels['voice_msg_behavior'] = Reels['voice_msg_behavior'].fillna(mode_value)

In [36]:
Reels.isnull().sum()  #it shows No of null values

timestamp                     0
age_group                     0
gender                        0
region                        0
marital_status                0
occupation                    0
education_level               0
primary_platform              0
daily_watch_hours             0
content_type                  0
peak_usage_time               0
daily_opens                   0
voice_msg_behavior            0
usage_duration_since          0
content_relevance             0
difficulty_closing_app        0
productivity_impact           0
sleep_impact                  0
feeling_after_closing         0
watching_companion            0
behavior_while_watching       0
phone_during_family           0
family_opinion                0
reason_for_watching           0
social_media_without_reels    0
purchased_from_video          0
purchase_reason               0
purchase_influence_level      0
rewatched_before_purchase     0
watch_intensity_score         0
user_segment                  0
content_count                 0
user_id                       0
dtype: int64

In [37]:
Reels.drop('timestamp', axis=1, inplace=True)

In [38]:
#Reels.to_excel("C:\\Users\\omnia\\OneDrive\\Desktop\\Data_Engineering\\Reals_Project\\Reels.xlsx", index=False)